### 자바 예외 계층

<img src="https://github.com/user-attachments/assets/dd201f72-2df2-4e74-9f6f-ad45a81612f6">

* Object : 예외도 객체이며 모든 객체의 최상위 부모는 Object 이므로 예외의 최상위 부모도 Object 이다.

* Throwable : 최상위 예외. 하위에 Exception 과 Error 가 있다.

* Error : 메모리 부족이나 심각한 시스템 오류와 같이 애플리케이션에서 복구 불가능한 시스템 예외. 애플리케이션 개발자는 이 예외를 잡으려고 해서는 안된다.

    - 상위 예외를 catch 로 잡으면 그 하위 예외까지 함께 잡는다. 

    - 따라서 애플리케이션 로직에서는 Throwable 예외도 잡으면 안되는데, 앞서 이야기한 Error 예외도 함께 잡을 수 있기 때문이다. 

    - 애플리케이션 로직은 이런 이유로 Exception 부터 필요한 예외로 생각하고 잡으면 된다.

    - Error 도 언체크 예외이다.

* Exception : 체크 예외

    - 애플리케이션 로직에서 사용할 수 있는 실질적인 최상위 예외이다.

    - RuntimeException 을 제외한 Exception 과 그 하위 예외는 모두 컴파일러가 체크하는 체크 예외이다.

* RuntimeException : 언체크 예외, 런타임 예외

    - 컴파일러가 체크 하지 않는 언체크 예외.

    - RuntimeException 과 그 자식 예외는 모두 언체크 예외이다.

    - RuntimeException 의 이름을 따라서 RuntimeException 과 그 하위 언체크 예외를 런타임 예외라고 많이 부른다.

### 예외 기본 규칙

* 예외는 처리하거나, 호출한 곳으로 던져야 한다

    - 리포지토리 계층에서 예외 발생 시 예외처리를 했다면 그걸로 예외는 끝난다

    - 처리하지 못하면 해당 메서드를 서비스 계층으로(호출한 쪽으로) 예외를 던진다

    - 서비스 계층에서 처리 못할 시 was 까지 던져져서 사용자에게 개발자가 지정한 오류 페이지를 보여준다

### 체크 예외

* RuntimeException 을 제외한 Exception 과 그 하위 예외

* 잡아서 처리하거나, 밖으로 던지도록 선언해야한다. 그렇지 않으면 컴파일 오류가 발생한다

* Exception 을 상속받으면 체크 예외가 된다

```java
// test
@Slf4j
public class CheckedTest {

    @Test
    void checked_catch(){
        Service service = new Service();
        service.callCatch();
    }

    // 예외가 테스트 메서드까지 올라온다
    // 테스트는 MyCheckException 예외가 던져지면 성공으로 처리한다
    @Test
    void checked_throw(){
        Service service = new Service();
        Assertions.assertThatThrownBy(service::callThrow)
                .isInstanceOf(MyCheckException.class);
    }

    /**
     * Exception 을 상속받은 에외는 체크 에외가 된다
     */
    static class MyCheckException extends Exception{
        public MyCheckException(String message){
            super(message);
        }
    }

    /**
     * Checked 예외는
     * 예외를 잡아서 처리하거나, 던지거나 둘 중 하나를 필수로 선택해야 한다
     */
    static class Service{
        Repository repository = new Repository();

        /**
         * 예외를 잡아서 처리하는 코드
         */
        public void callCatch(){
            try {
                repository.call();

            // catch에 예외를 지정하면 해당 예외와 하위 타입 예외를 모두 잡아준다
            // 그래서 상위 타입인 Exception 을 지정해도 MyCheckException 을 잡을 수 있지만 
            // 정확하게 MyCheckException 만 잡고 싶다면 MyCheckException 을 지정해야 한다
            } catch (MyCheckException e) {
                // 예외 처리 로직
                log.info("예외 처리, message={}", e.getMessage(), e);
            }
        }

        /**
         * 체크 예외를 밖으로 던지는 코드
         * 체크 예외는 예외를 잡지 않고 밖으로 던지려면 throws 예외를 메서드에 필수로 선언해야 한다.
         * throws 에 지정한 타입과 하위 타입 예외를 던지기 때문에 Exception 을 적어도 MyCheckException 을 던질 수 있지만, 정확하게 적어주는 것이 좋다
         */
        public void callThrow() throws MyCheckException {
            repository.call();
        }
    }

    static class Repository{
        public void call() throws MyCheckException {
            throw new MyCheckException("ex");
        }
    }
}
```
### 언체크 예외

* RuntimeException 과 그 하위 예외

* 컴파일러가 예외를 체크하지 않는다.

* 예외를 잡거나 처리하는 기본적인 규칙은 체크 예외와 같지만, 예외를 던지는 throws 를 선언하지 않고, 생략할 수 있다. 이 경우 자동으로 예외를 던진다.

* RuntimeException 을 상속받으면 언체크 예외가 된다

```java
// test
@Slf4j
public class UncheckedTest {

    @Test
    void unchecked_catch(){
        Service service = new Service();
        service.callCatch();
    }

    @Test
    void unchecked_throw(){
        Service service = new Service();
        assertThatThrownBy(() -> service.callThrow())
                .isInstanceOf(MyUncheckedException.class);
    }

    /**
     * RuntimeException 을 상속받은 예외는 언체크 예외가 된다
     */
    static class MyUncheckedException extends RuntimeException{
        public MyUncheckedException(String message){
            super(message);
        }
    }

    /**
     * UnChecked 예외는
     * 예외를 잡거나, 던지지 않아도 된다.
     * 예외를 잡지 않으면 자동으로 밖으로 던진다.
     */
    static class Service{
        Repository repository = new Repository();

        /**
         * 필요한 경우 예외를 잡아서 처리하면 된다.
         */
        public void callCatch(){

            try {
                repository.call();
            } catch (MyUncheckedException e){
                // 예외 처리 로직
                log.info("예외 처리, message={}", e.getMessage(), e);
            }
        }

        /**
         * 예외를 잡지 않아도 된다. 자연스럽게 상위로 넘어간다.
         * 체크 예외와 다르게 throws 예외 선언을 하지 않아도 된다.
         */
        public void callThrow(){
            repository.call();
        }
    }

    static class Repository{
        public void call(){
            throw new MyUncheckedException("ex");
        }
    }
}
```
